// **********************************************
// Copyright (c) 2013 SPORT Lab(http://atrak.usc.edu/~sport/),
// University of Southern California
// **********************************************
#include <boost/bind.hpp>
#include <boost/lambda/lambda.hpp>
#include "sources/IdealVoltageSource.h"

CIdealVoltageSource::CIdealVoltageSource(void) {
	_voltage = 5;

	// Add properties
    _AddProperty(new CProperty("voltage", "Source voltage.",
        InvalidSetter,
        boost::bind(SimpleGetter<double>, _1, boost::ref(_voltage)),
        boost::bind(CheckSetter<double>, _1, boost::ref(_voltage), (boost::lambda::_1 > 0))));
    _AddProperty(new CProperty("generation", "Total energy generated by this source.",
        boost::bind(SimpleGetter<double>, _1, boost::ref(_generation))));
    _AddProperty(new CProperty("current", "Power generated.",
        boost::bind(SimpleGetter<double>, _1, boost::ref(_portCurrent))));
}

CIdealVoltageSource::~CIdealVoltageSource() {
}

void CIdealVoltageSource::Reset() {
	_generation = 0;
}

double CIdealVoltageSource::PortVoltage(double time, double current) const {
	return _voltage;
}

double CIdealVoltageSource::MaxOutPortCurrent(double time) const {
	return INF;
}

void CIdealVoltageSource::TimeElapse(double time, double timeElapsed) {
	_generation += -_portCurrent*_voltage*timeElapsed;
}

double CIdealVoltageSource::GetEnergyGeneration() {
	return _generation;
}

double CIdealVoltageSource::NextTimeStep(double time, int precision) const {
	return INF;
}
